name: openff-env
channels:
    - conda-forge
dependencies:
    - jupyterlab
    - openff-toolkit-examples>=0.19.0 # Need at least 0.17.0 for NAGL compat.
    - openff-interchange>=0.5.4 # Need at least 0.4.7 for NAGL compat.
    - packmol # Needed to pack water box only
    - ambertools # Needed for AM1-BCC charge assignment comparison only
    - MDAnalysis
    - prolif
    - py3dmol # For 3D visualization of of interactions in prolif
    - openbabel # For conversion of the pdbqt files to sdf (last exercise)
